import React from "react";

const Disclaimer = () => {
  return (
    <div className="container">
      <div id="cookie">
        <h2 className="cookie-head">Disclaimer</h2>
        <p>Updated at 2021-11-11</p>
        <p>
          Digiapricus hereby grants you access to <a href="https://digiapricus.com/">https://digiapricus.com/</a> (“the
          Website”) and invites you to purchase the services offered here.
        </p>
        <h2>Definitions and key terms</h2>
        <p>
          To help explain things as clearly as possible in this Disclaimer,
          every time any of these terms are referenced, are strictly defined as:
        </p>
        <ul>
          <li>
            <span>Cookie:</span>
            <p>
              small amount of data generated by a website and saved by your web
              browser. It is used to identify your browser, provide analytics,
              remember information about you such as your language preference or
              login information.
            </p>
          </li>
          <li>
            <span> Company:</span>
            <p>
              when this policy mentions “Company,” “we,” “us,” or “our,” it
              refers to Digiapricus Private Limited, K V MURALI BANK COLONY
              GOWRIBIDANUR CHIKKABALLAPUR Bangalore KA 561208 IN that is
              responsible for your information under this Disclaimer.
            </p>
          </li>
          <li>
            <span>Service:</span>
            <p>
              Refers to the service provided by Digiapricus as described in the
              relative terms (if available) and on this platform.
            </p>
          </li>
          <li>
            <span>Website:</span>
            <p>
              Digiapricus."’s" site, which can be accessed via this URL:
              <a href="https://digiapricus.com/">https://digiapricus.com/</a>
            </p>
          </li>
          <li>
            <span>You:</span>
            <p>
              A person or entity that is registered with Digiapricus to use the
              Services.
            </p>
          </li>
        </ul>
        <h2>Limited liability</h2>
        <div className="liability-p">
          <p>
            Digiapricus endeavours to update and/or supplement the content of
            the website on a regular basis. Despite our care and attention,
            content may be incomplete and/or incorrect.
          </p>
          <p>
            The materials offered on the website are offered without any form of
            guarantee or claim to their correctness. These materials can be
            changed at any time without prior notice from Digiapricus.
          </p>
          <p>
            Particularly, all prices on the website are stated subject to typing
            and programming errors. No liability is assumed for the implications
            of such errors. No agreement is concluded on the basis of such
            errors.
          </p>
          <p>
            Digiapricus shall not bear any liability for hyperlinks to websites
            or services of third parties included on the website. From our
            website, you can visit other websites by following hyperlinks to
            such external sites. While we strive to provide only quality links
            to useful and ethical websites, we have no control over the content
            and nature of these sites. These links to other websites do not
            imply a recommendation for all the content found on these sites.
            Site owners and content may change without notice and may occur
            before we have the opportunity to remove a link which may have gone
            ‘bad’.
          </p>
          <p>
            Please be also aware that when you leave our website, other sites
            may have different privacy policies and terms which are beyond our
            control. Please be sure to check the Privacy Policies of these sites
            as well as their "Terms of Service" before engaging in any business
            or uploading any information.
          </p>
        </div>
        <h2>Links to Other Websites Disclaimer</h2>
        <div className="liability-p">
          <p>
            This Disclaimer applies only to the Services. The Services may
            contain links to other websites not operated or controlled by
            Digiapricus. We are not responsible for the content, accuracy or
            opinions expressed in such websites, and such websites are not
            investigated, monitored or checked for accuracy or completeness by
            us. Please remember that when you use a link to go from the Services
            to another website, our Privacy Policy is no longer in effect. Your
            browsing and interaction on any other website, including those that
            have a link on our platform, is subject to that website’s own rules
            and policies. Such third parties may use their own cookies or other
            methods to collect information about you. If You click on a third
            party link, You will be directed to that third party's site. We
            strongly advise You to review the Privacy Policy and Terms of every
            site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
        </div>
        <h2>Errors and Omissions Disclaimer</h2>
        <div className="liability-p">
          <p>
            Digiapricus is not responsible for any content, code or any other
            imprecision.
          </p>
          <p>Digiapricus does not provide warranties or guarantees.</p>
          <p>
            In no event shall Digiapricus be liable for any special, direct,
            indirect, consequential, or incidental damages or any damages
            whatsoever, whether in an action of contract, negligence or other
            tort, arising out of or in connection with the use of the Service or
            the contents of the Service. Digiapricus reserves the right to make
            additions, deletions, or modifications to the contents on the
            Service at any time without prior notice.
          </p>
        </div>
        <h2>General Disclaimer</h2>
        <p>
          The Digiapricus Service and its contents are provided "as is" and "as
          available" without any warranty or representations of any kind,
          whether express or implied. Digiapricus is a distributor and not a
          publisher of the content supplied by third parties; as such,
          Digiapricus exercises no editorial control over such content and makes
          no warranty or representation as to the accuracy, reliability or
          currency of any information, content, service or merchandise provided
          through or accessible via the Digiapricus Service. Without limiting
          the foregoing, Digiapricus specifically disclaims all warranties and
          representations in any content transmitted on or in connection with
          the Digiapricus Service or on sites that may appear as links on the
          Digiapricus Service, or in the products provided as a part of, or
          otherwise in connection with, the Digiapricus Service, including
          without limitation any warranties of merchantability, fitness for a
          particular purpose or non-infringement of third party rights. No oral
          advice or written information given by Digiapricus or any of its
          affiliates, employees, officers, directors, agents, or the like will
          create a warranty. Price and availability information is subject to
          change without notice. Without limiting the foregoing, Digiapricus
          does not warrant that the Digiapricus Service will be uninterrupted,
          uncorrupted, timely, or error-free.
        </p>
        <h2>Copyright Disclaimer</h2>
        <p>
          All intellectual property rights concerning these materials are vested
          in Digiapricus. Copying, distribution and any other use of these
          materials is not permitted without the written permission of
          Digiapricus, except and only to the extent otherwise provided in
          regulations of mandatory law (such as the right to quote), unless
          otherwise stated for certain materials.
        </p>
        <h2>Legal Disclosure</h2>
        <p>
          The materials, any comments or information provided by Digiapricus are
          for educational purposes only and nothing conveyed or provided should
          be considered legal, accounting or tax advice. You are responsible for
          whatever you may do with the information you obtain from Digiapricus.
          As such, by visiting and using this website you acknowledge and agree
          that you have been assessed by a qualified law expert (i.e your
          attorney) who has given you consent to take part in any legal
          activity. Please contact your own attorney, accountant or tax
          professional with any specific questions you have related to the
          information provided that are of legal, accounting or tax nature.
        </p>
        <h2>Educational Disclosure</h2>
        <p>
          Any Information provided by Digiapricus is for educational purposes
          only, and is not to be interpreted as a recommendation for a specific
          treatment plan, product, or course of action. Digiapricus is a
          distributor and not a publisher of the content supplied by third
          parties; as such, Digiapricus exercises no editorial control over such
          content and makes no warranty or representation as to the accuracy,
          reliability or currency of any information or educational content
          provided through or accessible via Digiapricus. Without limiting the
          foregoing, Digiapricus specifically disclaims all warranties and
          representations in any content transmitted on or in connection with
          Digiapricus or on sites that may appear as links on Digiapricus, or in
          the products provided as a part of, or otherwise in connection with,
          the Digiapricus. No oral advice or written information given by
          Digiapricus or any of its affiliates, employees, officers, directors,
          agents, or the like will create a warranty.
        </p>
        <h2>Testimonials Disclosure</h2>
        <div className="liability-p">
          <p>
            Any testimonials provided on this platform are opinions of those
            providing them. The information provided in the testimonials is not
            to be relied upon to predict results in your specific situation. The
            results you experience will be dependent on many factors including
            but not limited to your level of personal responsibility,
            commitment, and abilities, in addition to those factors that you
            and/or Digiapricus may not be able to anticipate.
          </p>
          <p>
            We will give honest testimonials to our visitors regardless of any
            discount. Any product or service that we test are individual
            experiences, reflecting real life experiences. The testimonials
            could be displayed on audio, text or video and are not necessarily
            representative of all of those who will use our products and/or
            services.
          </p>
          <p>
            Digiapricus does not guarantee the same results as the testimonials
            given on our platform. Testimonials presented on Digiapricus are
            applicable to the individuals writing them, and may not be
            indicative of future success of any other individuals.
          </p>
          <p>
            Please don’t hesitate to contact us if you would like to know more
            about testimonials, discounts, or any of the products/services that
            we review.
          </p>
        </div>
        <h2>Your Consent</h2>
        <p>
          We've updated our Disclaimer to provide you with complete transparency
          into what is being set when you visit our site and how it's being
          used. By using our website, registering an account, or making a
          purchase, you hereby consent to our Disclaimer and agree to its terms.
        </p>
        <h2>Changes To Our Disclaimer</h2>
        <p>
          Should we update, amend or make any changes to this document so that
          they accurately reflect our Service and policies. Unless otherwise
          required by law, those changes will be prominently posted here. Then,
          if you continue to use the Service, you will be bound by the updated
          Disclaimer. If you do not want to agree to this or any updated
          Disclaimer, you can delete your account.
        </p>
        <h2>Contact Us</h2>

        <p>
          Don't hesitate to contact us if you have any questions regarding this
          Disclaimer.
        </p>
        <p>● Via Email: <a href="#">info@digiapricus.com</a></p>
        <p>● Via Phone Number: 8088191336</p>
        <p>● Via this Link: <a href="https://digiapricus.com">https://digiapricus.com/</a></p>
      </div>
    </div>
  );
};

export default Disclaimer;
