import React from "react";

const ReturnRefund = () => {
  return (
    <div className="container">
      <div id="cookie">
        <h2 className="cookie-head">Return & Refund Policy</h2>
        <p>Updated at 2021-11-11.</p>
        <h2>Definitions and key terms</h2>
        <div className="liability-p">
          <p>
            To help explain things as clearly as possible in this Return &
            Refund Policy, every time any of these terms are referenced, are
            strictly defined as:
          </p>
          <ul>
            <li>
              <span> Cookie:</span>
              <p>
                Small amount of data generated by a website and saved by your
                web browser. It is used to identify your browser, provide
                analytics, remember information about you such as your language
                preference or login information.
              </p>
            </li>
            <li>
              <span> Company: </span>
              <p>
                When this policy mentions “Company,” “we,” “us,” or “our,” it
                refers to Digiapricus, that is responsible for your information
                under this Return & Refund Policy.
              </p>
            </li>
            <li>
              <span>Customer:</span>
              <p>
                Refers to the company, organization or person that signs up to
                use the Digiapricus Service to manage the relationships with
                your consumers or service users.
              </p>
            </li>
            <li>
              <span> Device:</span>
              <p>
                Any internet connected device such as a phone, tablet, computer
                or any other device that can be used to visit Digiapricus and
                use the services.
              </p>
            </li>
            <li>
              <span> Service:</span>
              <p>
                Refers to the service provided by Digiapricus as described in
                the relative terms (if available) and on this platform.
              </p>
            </li>
            <li>
              <span>Website:</span>
              <p>
                Digiapricus."’s" site, which can be accessed via this URL:{" "}
                <a href="https://digiapricus.com">https://digiapricus.com/</a>
              </p>
            </li>
            <li>
              <span>You:</span>
              <p>
                A person or entity that is registered with Digiapricus to use
                the Services.
              </p>
            </li>
          </ul>
        </div>
        <h2>Return & Refund Policy</h2>
        <div className="liability-p">
          <p>
            Thanks for shopping at Digiapricus. We appreciate the fact that you
            like to buy the stuff we build. We also want to make sure you have a
            rewarding experience while you’re exploring, evaluating, and
            purchasing our products.
          </p>
          <p>
            As with any shopping experience, there are terms and conditions that
            apply to transactions at Digiapricus. We’ll be as brief as our
            attorneys will allow. The main thing to remember is that by placing
            an order or making a purchase at Digiapricus, you agree to the terms
            set forth below along with Policy.
          </p>
          <p>
            If there’s something wrong with the product/service you bought, or
            if you are not happy with it, you have 2 weeks to issue a refund and
            return your product/service.
          </p>
          <p>
            If you would like to return a product, the only way would be if you
            follow the next guidelines:
          </p>
        </div>
        <h2>Refunds</h2>
        <div className="liability-p">
          <p>
            We at ourselves to serving our customers with the best products.
            Every single product that you choose is thoroughly inspected,
            checked for defects and packaged with utmost care. We do this to
            ensure that you fall in love with our products.
          </p>
          <p>
            Sadly, there are times when we may not have the product(s) that you
            choose in stock, or may face some issues with our inventory and
            quality check. In such cases, we may have to cancel your order. You
            will be intimated about it in advance so that you don't have to
            worry unnecessarily about your order. If you have purchased via
            Online payment (not Cash on Delivery), then you will be refunded
            once our team confirms your request.
          </p>
          <p>
            We carry out thorough quality check before processing the ordered
            item. We take utmost care while packing the product. At the same
            time we ensure that the packing is good such that the items won’t
            get damaged during transit. Please note that Digiapricus is not
            liable for damages that are caused to the items during transit or
            transportation.
          </p>
          <p>
            We will revise your returned product as soon as we receive it and if
            it follows the guidelines addressed above, we will proceed to issue
            a refund of your purchase. Your refund may take a couple of days to
            process but you will be notified when you receive your money.
          </p>
        </div>
        <h2>Shipping</h2>
        <p>
          Digiapricus is not responsible for return shipping costs. Every
          shipping has to be paid by the customer, even if the item had free
          shipping in the first place, the customer has to pay for the shipping
          in return.
        </p>
        <h2>Your Consent</h2>
        <p>
          By using our website, registering an account, or making a purchase,
          you hereby consent to our Return & Refund Policy and agree to its
          terms.
        </p>
        <h2>Changes To Our Return & Refund Policy</h2>
        <p>
          Should we update, amend or make any changes to this document so that
          they accurately reflect our Service and policies. Unless otherwise
          required by law, those changes will be prominently posted here. Then,
          if you continue to use the Service, you will be bound by the updated
          Return & Refund Policy. If you do not want to agree to this or any
          updated Return & Refund Policy, you can delete your account.
        </p>

        <h2>Contact Us</h2>
        <p>
          If, for any reason, You are not completely satisfied with any good or
          service that we provide, don't hesitate to contact us and we will
          discuss any of the issues you are going through with our product.
        </p>
        <div className="personal-data">
          <p>
            ● Via Email: <a href="#">info@digiapricus.com</a>
          </p>
          <p>● Via Phone Number: 8088191336</p>
        </div>
      </div>
    </div>
  );
};

export default ReturnRefund;
